accelerator: gpu
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_norm: false
batch_size: 16
bce_loss_weight: 1.0
benchmark: null
best_checkpoint: null
cache_path: tmp/example_dataset_cache_split.pt
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_path: null
crv_emb_dim: 64
debug_data: true
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: '1'
e_in_width: 72
enable_blacklist: true
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
exact_match_labels: false
f_in_width: 62
fast_dev_run: false
fflayers: 6
flush_logs_every_n_steps: null
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
init_keep_ratio: 1.0
init_strategy: exact
ipus: null
l_in_width: 38
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 1000
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
mp_cur_matches: true
mp_exact_matches: false
mp_overlap_matches: false
multiple_trainloader_mode: max_size_cycle
name: debug_by_pyfemtet
no_test: false
no_train: false
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_thresholds: 10
num_workers: 1
overfit_batches: 0.0
override_args: false
persistent_workers: true
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
resume_version: null
save_data: false
sbgcn_size: 64
seed: 42
shuffle: true
single_set: false
srf_emb_dim: 64
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
tensorboard_path: .
terminate_on_nan: null
test_adjacency: false
test_batch_size: null
test_greedy: true
test_identity: false
test_iterative_vs_threshold: true
test_size: 0.1
threshold: 0.75
tpu_cores: null
track_grad_norm: -1
train_init_keep_ratio: 0.5
train_random_init_keep_ratio: false
use_onshape: none
use_uvnet_features: false
v_in_width: 3
val_batch_size: null
val_check_interval: null
val_greedy: false
val_iter: false
val_size: 0.1
validate: false
weights_save_path: null
weights_summary: top
zip_path: data/example_dataset.zip
